### ISSUE TITLE
关于run_train.py中net指定gpu的问题

### ISSUE THREAD

**Issue by sodalone** [xytpai/fcos#15]
net = torch.nn.DataParallel(net, device_ids=cfg['device'])
net = net.cuda(cfg['device'][0])
net.train()
这是在run_train.py中准备model时候的操作。
想请问，为什么先分配到所有的gpu上`net = torch.nn.DataParallel(net, device_ids=cfg['device'])`，然后再单独指定一块`net = net.cuda(cfg['device'][0])`？不太清楚其中意义。

希望能够获得答复，谢谢！

**Comment by xytpai** [comment]
这个项目用的是pytorch 1.0，多卡训练的梯度是在所指定的第一块卡中做平均的，按要求先得把参数传到第一块卡

**Comment by sodalone** [comment]
谢谢！刚刚有查阅官方文档，给出的demo也是这样。谢谢，麻烦你了！
[官方文档](https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html#create-model-and-dataparallel)
