### ISSUE TITLE
关于centerness

### ISSUE THREAD

**Issue by Rock-100** [xytpai/fcos#7]
您好，请问你把centerness去掉后，不会引起误检测变多么？我看原文中这是一个创新点

**Comment by xytpai** [comment]
如果只把每一个物体的中心当作正例，其实它也会得到一个类似centerness的分布。个人认为centerness不是特别重要。

**Comment by Rock-100** [comment]
@xytpai 感谢回复！另外，请问有没有coco训练好的模型可以测试一下？好像这个project里没放模型

**Comment by xytpai** [comment]
已经更新模型参数链接，参见readme

**Comment by Rock-100** [comment]
@xytpai  cool，thank you！
