### ISSUE TITLE
assign box中的参数

### ISSUE THREAD

**Issue by Rock-100** [xytpai/fcos#8]
你好，请问如果修改训练时候图像的输入尺寸，1024，200,5这几个数字需要修改吗？比如要修改成256*896大小训练
![微信截图_20191226165800](https://user-images.githubusercontent.com/38135837/71483723-11fb9480-2801-11ea-902f-3a060fc685ae.png)

**Comment by xytpai** [comment]
这个不需要动的，这个1024是GPU每个Block分配的线程数目，如果你的GPU算力>=6.1可以用1024，如果算力低的话才需要调整。

**Comment by Rock-100** [comment]
@xytpai  好的，明白了！
