### ISSUE TITLE
训练coco时候，focal loss不能正常收敛

### ISSUE THREAD

**Issue by Rock-100** [xytpai/fcos#9]
你好，我用这个代码，训练coco2017数据集，发现focal loss不能正常收敛，完全偏向了负样本，正样本的分类准确率为0。我使用python3.7和pytorch1.0，batch size为8。请问你有什么经验和建议么
![微信截图_20191228201806](https://user-images.githubusercontent.com/38135837/71549085-7a887400-29af-11ea-8b3a-a8da9473af66.png)

**Comment by xytpai** [comment]
应该是迭代次数不够

**Comment by Rock-100** [comment]
@xytpai 已解决，是我算acc算错了，fcos和retinanet一样，用的是sigmod，不是softmax
